INSERT INTO `phpapp_language` (`id_phpapp`, `name_phpapp`, `dir_phpapp`, `domain_phpapp`, `style_phpapp`, `status_phpapp`) VALUES
(1, '中国', 'cn', 'demo.phpapp.cn', 'china-cn', 0),
(2, '中國台灣', 'tw', 'tw.phpapp.cn', 'china-tw', 0),
(3, 'USA', 'en', 'en.phpapp.cn', 'engish', 0),
(7, 'Italy', 'it', 'it.phpapp.cn', 'italy', 0),
(4, 'France', 'fr', 'fr.phpapp.cn', 'france', 0),
(5, 'Germany', 'de', 'de.phpapp.cn', 'germany', 0),
(6, '中國香港', 'hk', 'hk.phpapp.cn', 'china-hk', 0),
(8, 'Japan', 'jp', 'jp.phpapp.cn', 'japan', 0),
(9, 'Korea', 'kr', 'kr.phpapp.cn', 'korea', 0),
(10, 'Mexico', 'mx', 'mx.phpapp.cn', 'mexico', 0),
(11, 'Portugal', 'pt', 'pt.phpapp.cn', 'portugal', 0),
(12, 'Sweden', 'se', 'se.phpapp.cn', 'sweden', 0),
(13, 'Thailand', 'th', 'th.phpapp.cn', 'thailand', 0),
(14, 'England', 'gb', 'gb.phpapp.cn', 'greatbritain', 0),
(15, 'Canada', 'ca', 'ca.phpapp.cn', 'canada', 0);


INSERT INTO `phpapp_bankname` (`bankid`, `bankname`) VALUES
(1, '中国农业银行'),
(2, '中国工商银行'),
(3, '中国建设银行');


INSERT INTO `phpapp_certificate` (`id_phpapp`, `app_phpapp`, `table_phpapp`, `name_phpapp`, `type_phpapp`, `icon_small_phpapp`, `icon_middle_phpapp`, `icon_big_phpapp`, `description_phpapp`, `price_phpapp`, `time_phpapp`, `status_phpapp`) VALUES
(1, 14, 'member_mail_certificate', '邮箱认证', 0, '', '', 'email_icon_big', '<b>邮箱地址登录</b> 可直接使用“邮箱地址”登录<br>\r\n<b>重要事件提醒 </b>进行（支付/提现/选稿/中标）时，自动发送提醒<br>\r\n<b>找回账号密码</b> 忘记密码时，可使用邮件找回密码。\r\n ', '0.00', 1, 0),
(2, 21, 'member_mobile_certificate', '手机认证', 0, 'mobile_icon_small', '', 'mobile_icon_big', '<b>手机登录</b> 可直接使用“手机”登录<br>\n<b>重要事件提醒 </b>进行（支付/提现/选稿/中标）时，自动发送提醒<br>\n<b>找回账号密码</b> 忘记密码时，可使用手机短信找回密码。', '0.00', 1, 0),
(3, 15, 'member_personal_certificate', '实名认证', 1, '', '', 'realname_icon_big', '<b>实名认证</b>  可参与诚信交易的任务\r\n<p>并可将金额提现到您已认证的银行卡上。</p>\r\n', '0.00', 3, 0),
(4, 16, 'member_company_certificate', '实名认证', 2, '', '', 'company_icon_big', '<b>实名认证</b>  可参与诚信交易的任务\n<p>并可将金额提现到您已认证的银行卡上。</p>', '0.00', 1, 0),
(5, 26, 'member_vip', 'VIP会员', 0, 'member_vip_ico', '', 'member_vip_icon_big', '<b>VIP会员</b> 可享受网站特权与服务<br>\r\n例如：购买道具优惠，任务开通高级权限等<br>\r\n申请前要需要 \"手机认证\" 和 \"实名认证\" 认证通过。', '100.00', 1, 0);



INSERT INTO `phpapp_config` (`app_phpapp`, `name_phpapp`, `value_phpapp`) VALUES
(1, 'sitename', 'PHPAPP威客系统'),
(1, 'uc_apitype', '0'),
(1, 'uc_dbuser', 'root'),
(1, 'uc_dbpw', 'root'),
(1, 'uc_dbpre', 'uc_'),
(1, 'uc_dbcharset', 'gbk'),
(1, 'uc_charset', 'gbk'),
(1, 'uc_key', 'LHJCR78I24DXFG5'),
(1, 'uc_ip', ''),
(1, 'uc_appid', '1'),
(1, 'uc_api', 'http://localhost/ucenter'),
(1, 'uc_open', '0'),
(1, 'uc_dbname', 'phpapp'),
(1, 'uc_dbhost', 'localhost'),
(1, 'cookie_domain', ''),
(1, 'cookie_path', ''),
(1, 'cookie_time', '604800'),
(1, 'register_agreement', '测试</br>测试'),
(1, 'paygoodsname', '威客充值'),
(1, 'paydescription', '威客充值内容'),
(1, 'alipaymail', ''),
(1, 'alipayid', ''),
(1, 'alipaykey', ''),
(1, 'timezone', '8'),
(14, 'mailsmtp', 'smtp.163.com'),
(14, 'mailsmtpport', '25'),
(14, 'mailloginname', ''),
(14, 'mailloginpassword', ''),
(14, 'sitemail', ''),
(14, 'mailos', '1'),
(14, 'mailsendcharset', '0'),
(14, 'mailsendsystem', '1'),
(14, 'sendmailmode', '1'),
(5, 'pay_small_money', '1'),
(15, 'smallverifymoney', '0.2'),
(5, 'withdrawsmall', '10'),
(5, 'withdrawnum', '3'),
(5, 'withdrawbig', '20000'),
(18, 'uploadphototype', 'jpg,gif,png'),
(18, 'uploadfiletype', 'jpg,gif,png,rar,zip'),
(18, 'oneimageuploadsize', '819200'),
(18, 'totalimageuploadsize', '2048000'),
(18, 'onefileuploadsize', '819200'),
(18, 'totalfileuploadsize', '4096000'),
(18, 'isthumb', '0'),
(18, 'thumbwidth', '600'),
(18, 'thumbheight', '600'),
(18, 'watermarklogopath', 'images/watermark/logo.png'),
(18, 'watermarklogo', '0'),
(18, 'watermarkminimum', '400'),
(18, 'blackwatermark', '0'),
(1, 'seccodefont', 'phpapp/fonts/cetus.ttf'),
(1, 'sitefont', 'phpapp/fonts/wenq.ttf'),
(58, 'sinaappkey', ''),
(58, 'sinaappsecret', ''),
(59, 'qqweiboappkey', ''),
(59, 'qqweiboappsecret', ''),
(15, 'personalcertificatemoney', '1'),
(16, 'companycertificatemoney', '2'),
(65, 'qqappkey', ''),
(65, 'qqappsecret', ''),
(66, 'taobaoappkey', ''),
(66, 'taobaoappsecret', ''),
(67, 'neteaseappkey', ''),
(67, 'neteaseappsecret', ''),
(69, 'sohuappkey', ''),
(69, 'sohuappsecret', ''),
(21, 'mobilecertificatenumber', '2'),
(21, 'mobilecertificatetime', '24'),
(1, 'sitepayname', 'E付宝'),
(1, 'sitetitle', '网站首页'),
(1, 'sitekeywords', 'PHPAPP威客程序，威客系统'),
(1, 'sitedescription', 'PHPAPP威客程序，威客系统，威客程序下载，威客系统下载'),
(1, 'allowregisterusername', 'admin*,root*,管理员*,phpapp*,edoog*'),
(80, 'task_count_agree', '发布协议发布协议&lt;br&gt;发布协议发布协议&lt;br&gt;&lt;br&gt;&lt;br&gt;发布协议'),
(80, 'task_count_subject_help', '&lt;strong&gt;任务主题影响任务完成质量的重要因素。&lt;/strong&gt;\r\n    &lt;p&gt;\r\n      &lt;p&gt;好的任务主题能让报名者清晰直接地了解到您的需求，吸引到更多优秀的报名者。&lt;/p&gt;\r\n      &lt;p&gt;优秀的任务主题一般包括几点基本要求：清晰，完整，达意。&lt;/p&gt;\r\n    &lt;/p&gt;\r\n\r\n    &lt;h4&gt;参考案例：&lt;/h4&gt;\r\n    &lt;p&gt;\r\n      &lt;p&gt;主题样例1：请人代制作网站&lt;/p&gt;\r\n      &lt;p&gt;推荐修改为：服装类电子商务网站设计开发（区域：杭州）&lt;/p&gt;\r\n    &lt;/p&gt;\r\n    &lt;p&gt;\r\n      &lt;p&gt;主题样例2：有偿修图&lt;/p&gt;\r\n      &lt;p&gt;推荐修改为：寻高手将照片处理为艺术照效果！&lt;/p&gt;\r\n    &lt;/p&gt;\r\n    &lt;p&gt;\r\n      &lt;p&gt;主题样例3：有偿答问卷&lt;/p&gt;\r\n      &lt;p&gt;推荐修改为：填写《网购用户心理调查》问卷调查获酬劳（简单易得）&lt;/p&gt;\r\n    &lt;/p&gt;\r\n    &lt;p&gt;\r\n      &lt;p&gt;主题样例4：找人写程序&lt;/p&gt;\r\n      &lt;p&gt;推荐修改为：寻人制作类似windows计算机一样的计算器小程序，Java环境&lt;/p&gt;\r\n    &lt;/p&gt;'),
(80, 'task_count_content_help', '&lt;div&gt;通过尽量详细、准确的描述，让您的需求传达地更丰富明确，吸引到更多更优秀的参与者报名！&lt;/div&gt;\r\n\r\n  &lt;h4&gt;参考案例：&lt;/h4&gt;\r\n  &lt;strong&gt;&lt;div&gt;1.网站设计类&lt;/div&gt;&lt;/strong&gt;\r\n  &lt;div&gt;\r\n    &lt;div&gt;\r\n      &lt;p&gt;网站首页：&lt;/p&gt;\r\n      &lt;p&gt;拥有主要信息，登录窗口，热门信息等内容&lt;/p&gt;\r\n    &lt;/div&gt;\r\n    &lt;div&gt;\r\n      &lt;p&gt;个人首页：&lt;/p&gt;\r\n      &lt;p&gt;可以看到个人帐户信息，包括查询历史，消费记录等&lt;/p&gt;\r\n    &lt;/div&gt;\r\n    &lt;div&gt;\r\n      &lt;p&gt;推荐产品：&lt;/p&gt;\r\n      &lt;p&gt;放置推荐的商品，可以后台人为控制&lt;/p&gt;\r\n    &lt;/div&gt;\r\n    &lt;div&gt;\r\n      &lt;p&gt;今日特价：&lt;/p&gt;\r\n      &lt;p&gt;可更新页面，自动筛选后台设置过的特价产品&lt;/p&gt;\r\n    &lt;/div&gt;\r\n    &lt;div&gt;\r\n      &lt;p&gt;资质要求：&lt;/p&gt;\r\n      &lt;p&gt;有2年以上网页设计经验，包括完整的网站设计，后台功能&lt;/p&gt;\r\n    &lt;/div&gt;\r\n  &lt;/div&gt;\r\n  &lt;strong&gt;&lt;div&gt;2.Logo设计类&lt;/div&gt;&lt;/strong&gt;\r\n  &lt;div&gt;\r\n    &lt;div&gt;\r\n      &lt;p&gt;设计主题：&lt;/p&gt;\r\n      &lt;p&gt;有本产品的卡通人物特使——浣熊元素(附上创意说明)&lt;/p&gt;\r\n    &lt;/div&gt;\r\n    &lt;div&gt;\r\n      &lt;p&gt;重点内容：&lt;/p&gt;\r\n      &lt;p&gt;突出本品牌“时尚，青春”的特点，同时要包括本产品的名称&lt;/p&gt;\r\n    &lt;/div&gt;\r\n    &lt;div&gt;\r\n      &lt;p&gt;文件大小：&lt;/p&gt;\r\n      &lt;p&gt;要求150*150，提供psd源文件以及Jpg生成文件&lt;/p&gt;\r\n    &lt;/div&gt;\r\n    &lt;div&gt;\r\n      &lt;p&gt;资质要求：&lt;/p&gt;\r\n      &lt;p&gt;有3年以上品牌设计经验，可提供现成案例&lt;/p&gt;\r\n    &lt;/div&gt;\r\n  &lt;/div&gt;'),
(49, 'task_endtime', '7'),
(49, 'task_haoping', '1'),
(49, 'task_zhongping', '0'),
(49, 'task_chaping', '-1'),
(1, 'memcacheip', '127.0.0.1'),
(1, 'memcacheport', '11211'),
(83, 'task_grab_agree', '发布协议发布协议\r\n发布协议发布协议\r\n<br>\r\n发布协议'),
(83, 'task_grab_subject_help', '<strong>任务主题影响任务完成质量的重要因素。</strong>\r\n    <p>\r\n      <p>好的任务主题能让报名者清晰直接地了解到您的需求，吸引到更多优秀的报\r\n\r\n名者。</p>\r\n      <p>优秀的任务主题一般包括几点基本要求：清晰，完整，达意。</p>\r\n    </p>\r\n\r\n    <h4>参考案例：</h4>\r\n    <p>\r\n      <p>主题样例1：请人代制作网站\r\n\r\n</p>\r\n      <p>推荐修改为：服装类电子商务网站设计开发（区域：杭州）</p>\r\n    </p>\r\n    <p>\r\n      <p>主题样例2：有偿修图</p>\r\n      <p>推荐修改为：寻高手将照片处理为艺\r\n\r\n术照效果！</p>\r\n    </p>\r\n    <p>\r\n      <p>主题样例3：有偿答问卷</p>\r\n      <p>推荐修改为：填写《网购用户心理调查》问卷调查获酬劳（简单易得）</p>\r\n    </p>\r\n    \r\n\r\n<p>\r\n      <p>主题样例4：找人写程序</p>\r\n      <p>推荐修改为：寻人制作类似windows计算机一样的计算器小程序，Java环境</p>\r\n    </p>'),
(83, 'task_grab_content_help', '<div>通过尽量详细、准确的描述，让您的需求传达地更丰富明确，吸引到更多更优秀的参与者报名！</div>\r\n\r\n  <h4>参考案例：</h4>\r\n  \r\n\r\n<strong><div>1.网站设计类</div></strong>\r\n  <div>\r\n    <div>\r\n      <p>网站首页：</p>\r\n      <p>拥有主要信息，登录窗口，热门信息等内容</p>\r\n    </div>\r\n    <div>\r\n \r\n\r\n     <p>个人首页：</p>\r\n      <p>可以看到个人帐户信息，包括查询历史，消费记录等</p>\r\n    </div>\r\n    <div>\r\n      <p>推荐产品：</p>\r\n      <p>放置推荐的商品，可以后台\r\n\r\n人为控制</p>\r\n    </div>\r\n    <div>\r\n      <p>今日特价：</p>\r\n      <p>可更新页面，自动筛选后台设置过的特价产品</p>\r\n    </div>\r\n    <div>\r\n      <p>资质要求：\r\n\r\n</p>\r\n      <p>有2年以上网页设计经验，包括完整的网站设计，后台功能</p>\r\n    </div>\r\n  </div>\r\n  <strong><div>2.Logo设计类</div></strong>\r\n  <div>\r\n    <div>\r\n      \r\n\r\n<p>设计主题：</p>\r\n      <p>有本产品的卡通人物特使——浣熊元素(附上创意说明)</p>\r\n    </div>\r\n    <div>\r\n      <p>重点内容：</p>\r\n      <p>突出本品牌“时尚，青春”的特\r\n\r\n点，同时要包括本产品的名称</p>\r\n    </div>\r\n    <div>\r\n      <p>文件大小：</p>\r\n      <p>要求150*150，提供psd源文件以及Jpg生成文件</p>\r\n    </div>\r\n    <div>\r\n     \r\n\r\n <p>资质要求：</p>\r\n      <p>有3年以上品牌设计经验，可提供现成案例</p>\r\n    </div>\r\n  </div>'),
(1, 'sitecolor', '0'),
(1, 'siteclose', '0'),
(1, 'sitenotice', '1'),
(1, 'noticecontent', '通知：网站内测中 近期将开放注册'),
(1, 'closedreason', '网站关闭升级中...'),
(1, 'sitecount', ''),
(1, 'siteicp', ''),
(1, 'sitebanner', 'PHPAPP全球领先威客程序'),
(1, 'sitecodeaddtext1', '5'),
(1, 'sitecodeaddtext2', '10'),
(1, 'sitecodetype', '1'),
(1, 'sitecodefuzzy', '0'),
(1, 'textfilter', ''),
(28, 'phpappkey', ''),
(28, 'phpappsecret', ''),
(1, 'sys_operation_page', '12'),
(1, 'sys_operation_windowwidth', '980'),
(1, 'sys_operation_windowheight', '480'),
(1, 'sys_operation_windownum', '10'),
(1, 'sys_operation_windowerror', '窗口开太多了!'),
(1, 'sys_operation_iconwidth', '0'),
(1, 'sys_operation_backgroundcolor', '#EBEBEB'),
(21, 'mobilesmsuserid', ''),
(21, 'mobilesmspassword', ''),
(1, 'bankinfoset', '银行汇款信息\n<p>测试</p>'),
(1, 'sharecode', '<div id="ckepop">\r\n	<span class="jiathis_txt">分享到：</span>\r\n	<a class="jiathis_button_tsina">新浪微博</a>\r\n	<a class="jiathis_button_tqq">腾讯微博</a>\r\n	<a class="jiathis_button_renren">人人网</a>\r\n	<a class="jiathis_button_msn">MSN</a>\r\n	<a class="jiathis_button_taobao">淘江湖</a>\r\n	<a href="http://www.jiathis.com/share" class="jiathis jiathis_txt jiathis_separator jtico jtico_jiathis" target="_blank">更多</a>\r\n \r\n</div>\r\n<script type="text/javascript" src="http://v2.jiathis.com/code_mini/jia.js" charset="utf-8"></script> \r\n\r\n'),
(23, 'about', '&lt;p&gt;&lt;a href=&quot;http://www.phpapp.cn&quot;  target=&quot;_blank&quot;&gt;www.phpapp.cn&lt;/a&gt;&lt;/p&gt;'),
(23, 'contact', '&lt;a href=&quot;http://www.phpapp.cn&quot;  target=&quot;_blank&quot;&gt;www.phpapp.cn&lt;/a&gt;'),
(80, 'task_count_tourist', '0'),
(56, 'opensharecode', '1'),
(28, 'phpappauth', '0'),
(83, 'task_grab_tourist', '0'),
(49, 'task_auto_delivery', '7'),
(5, 'withdrawfee', '0.02'),
(85, 'taskguideid', '85'),
(82, 'task_seller_autodelivery', '3'),
(21, 'mobilesmsaccount', ''),
(18, 'watermarkname', '该作品于 {time} 由 {username} 上传到 www.phpapp.cn'),
(26, 'membervip', 'a:2:{i:1;a:1:{i:2;a:6:{s:3:"gid";s:1:"2";s:5:"price";s:3:"100";s:5:"level";s:9:"3|60,4|80";s:5:"money";s:2:"80";s:6:"demote";s:1:"3";s:5:"month";s:9:"3,6,12,24";}}i:2;a:1:{i:6;a:6:{s:3:"gid";s:1:"6";s:5:"price";s:3:"100";s:5:"level";s:4:"8|80";s:5:"money";s:3:"100";s:6:"demote";s:1:"7";s:5:"month";s:6:"3,6,12";}}}'),
(26, 'membervipdcription', '<b>会员特权</b>\r\n<p>一、购买所有道具免费</p>'),
(26, 'vipisopenmobile', '0'),
(15, 'personalisopenmobile', '0'),
(16, 'realcompanyisopenmobile', '0'),
(1, 'registeriscode', '1'),
(1, 'loginiscode', '1'),
(1, 'adminloginiscode', '1'),
(1, 'vipisopenrealname', '1'),
(1, 'rewrite_type', '0'),
(1, 'uc_linktype', 'mysql'),
(21, 'mobilecertificatenumber', '1'),
(82, 'task_seller_agree', '服务协议'),
(82, 'task_seller_phone', '0000-'),
(1, 'phpappversion', '20130826'),
(2, 'loginredirect', '0'),
(21, 'mobilesign', '【XX公司】'),
(7, 'smsscode', '0'),
(1, 'phpappinfoscode', '1'),
(20, 'uniontime', '365'),
(21, 'mobileusenumber', '1'),
(2, 'memberloginerrornum', '3'),
(2, 'memberloginerrortime', '15'),
(18, 'fileinfomime', '0'),
(18, 'ftp_open', '0'),
(18, 'ftp_server', ''),
(18, 'ftp_username', ''),
(18, 'ftp_password', ''),
(2, 'allowloginip', '0'),
(2, 'userdomainname', '0'),
(2, 'domainname', '.phpapp.cn'),
(2, 'allowdomainname', 'www|wwww|home|edoog|phpapp|root|admin'),
(2, 'domainnamesmall', '3'),
(2, 'domainnamelong', '7'),
(49, 'task_delay_time', '7'),
(80, 'task_count_tourist_content', '0'),
(83, 'task_grab_tourist_content', '0'),
(82, 'task_seller_tourist', '0'),
(1, 'setpagemode', '0'),
(1, 'setpagenumber', '500'),
(1, 'setsearchmode', '0'),
(1, 'setsearchnumber', '500'),
(26, 'membervipunionfee', '0.2'),
(1, 'templatepath', 'html'),
(1, 'stylepath', 'blue'),
(80, 'task_count_broaden_add', '10'),
(1, 'siteframewidth', '1000'),
(18, 'uploadmusictype', 'wma,mp3,rm'),
(48, 'task_auto_verifypay', '1'),
(2, 'sitecloseregister', '0'),
(49, 'task_check', '1'),
(5, 'realnamepaywithdraw', '0'),
(1, 'sitecloselanguage', '1'),
(1, 'sitecloseguide', '0'),
(1, 'registerednotice', '1'),
(1, 'registerednoticesubject', '尊敬的用户欢迎您！'),
(1, 'registerednoticecontent', '尊敬的用户欢迎您来到PHPAPP威客网！'),
(82, 'task_seller_payauto', '1'),
(49, 'task_releasemode', '0'),
(49, 'auto_delete_order_notice', '1'),
(42, 'orders_rights_date', '15'),
(48, 'task_auto_evaluate', '3'),
(49, 'task_assign_service', '1'),
(8, 'userspacestyle', '1');



INSERT INTO `phpapp_rewrite` (`id_phpapp`, `name_phpapp`, `original_phpapp`, `format_phpapp`, `displayorder_phpapp`, `status_phpapp`) VALUES
(1, 'RewriteLevel1', 'index.php?app={number}', '{abc}.html', 100, 0),
(2, 'RewriteLevel1A', 'index.php?app={number}{and}{all}', '{abc}.html{all}', 99, 0),
(3, 'RewriteLevel2', 'index.php?app={number}{and}action={number}', '{abc}/{abc}.html', 98, 0),
(4, 'RewriteLevel2A', 'index.php?app={number}{and}action={number}{and}{all}', '{abc}/{abc}.html{all}', 97, 0),
(5, 'RewriteLevel3', 'index.php?app={number}{and}action={number}{and}type={all}', '{abc}/{abc}/{abc}.html', 96, 0),
(6, 'RewriteLevel3A', 'index.php?app={number}{and}action={number}{and}type={all}{and}{all}', '{abc}/{abc}/{abc}.html{all}', 95, 0),
(7, 'RewriteLevel2B', 'index.php?app={number}{and}action={number}{and}{abc}={number}', '{abc}/{abc}/{abc}-{number}.html', 94, 0),
(8, 'RewriteLevel2C', 'index.php?app={number}{and}action={number}{and}{abc}={number}', '{abc}/{abc}/{abc}-{all}.html', 93, 0),
(9, 'RewriteLevel2D', '{abc}.php?app={number}', '(member|space|api|wap)/{abc}.html', 92, 0),
(10, 'RewriteLevel3B', '{abc}.php?app={number}{and}action={number}', '(member|space|api|wap)/{abc}/{abc}.html', 91, 0),
(11, 'RewriteLevel3C', '{abc}.php?app={number}{and}action={number}{and}{abc}={number}', '(member|space|api|wap)/{abc}/{abc}/{abc}-{number}.html', 90, 0),
(12, 'RewriteLevel3D', '{abc}.php?app={number}{and}action={number}{and}{abc}={number}{and}{abc}={number}', '(member|space|api|wap)/{abc}/{abc}/{abc}-{number}-{abc}-{number}.html', 89, 0),
(13, 'RewriteLevel2E', 'index.php?app={number}{and}action={number}{and}{abc}={number}{and}{abc}={number}', '{abc}/{abc}/{abc}-{number}-{abc}-{number}.html', 88, 0),
(14, 'RewriteLevel2F', 'index.php?app={number}{and}action={number}{and}{abc}={number}{and}{abc}={number}{and}{abc}={number}', '{abc}/{abc}/{abc}-{number}-{abc}-{number}-{abc}-{number}.html', 87, 0),
(15, 'RewriteLevel1B', 'index.php?app={number}{and}{abc}={number}', '{abc}/{abc}-{number}.html', 99, 0),
(16, 'RewriteLevel1C', 'index.php?app={number}{and}{abc}={number}{and}{abc}={number}', '{abc}/{abc}-{number}-{abc}-{number}.html', 99, 0),
(17, 'RewriteLevel2G', 'space.php?app=8{and}{abc}={number}', 'space/{abc}-{number}.html', 92, 0);